version: '3.8'

services:
  backend:
    build:
      context: ./chat-app-platform-nestjs
      dockerfile: backend.dockerfile
      target: development
    ports:
      - '3003:3003'
    volumes:
      - ./chat-app-platform-nestjs/src:/usr/src/src
    restart: unless-stopped

  frontend:
    build:
      context: ./chat-app-platform-react
      dockerfile: frontend.dockerfile
    ports:
      - '5173:80'
